services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-magento-app
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - ./.:/usr/src/app
      - ./public/images/tmp:/usr/src/app/public/images/tmp
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=nest_magento
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:17.0-alpine3.20
    container_name: nest-magento-db
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_magento
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
